# Generated by Django 5.2.4 on 2025-07-20 11:05

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('img', models.ImageField(default='fallback.jpg', upload_to='')),
                ('alt', models.CharField(blank=True, default='Capa do PDF', max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(blank=True, default='Anonymous', max_length=100)),
                ('ogdate', models.DateField(blank=True, default=datetime.date.today)),
                ('status', models.CharField(blank=True, choices=[('OK', 'Public, aproved!'), ('Waiting', 'Private, waiting for aproval...')], default='Waiting')),
            ],
            options={
                'verbose_name_plural': 'Books',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(default=1500, validators=[django.core.validators.MinValueValidator(1300), django.core.validators.MaxValueValidator(2200)])),
                ('title', models.CharField(max_length=100)),
                ('summary', models.CharField(max_length=150)),
                ('content', models.TextField(blank=True, max_length=500)),
                ('img', models.ImageField(default='fallback.jpg', upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='fallback.jpg', upload_to='')),
                ('author', models.CharField(default='Anonymous', max_length=100)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('canto', models.CharField(blank=True, choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V'), ('VI', 'VI'), ('VII', 'VII'), ('VIII', 'VIII'), ('IX', 'IX'), ('X', 'X')])),
                ('alt', models.CharField(blank=True, default='Image from workshop', max_length=100)),
                ('date', models.DateField(blank=True, verbose_name=datetime.date.today)),
                ('status', models.CharField(choices=[('OK', 'Public, aproved!'), ('Waiting', 'Private, waiting for aproval...')], default='Waiting')),
            ],
            options={
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.CreateModel(
            name='Lusiadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canto', models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V'), ('VI', 'VI'), ('VII', 'VII'), ('VIII', 'VIII'), ('IX', 'IX'), ('X', 'X')], default='I')),
                ('estrofe_id', models.CharField(max_length=4)),
                ('estrofe_pt', models.TextField(max_length=500)),
                ('estrofe_en', models.TextField(blank=True, max_length=500)),
                ('estrofe_note', models.TextField(blank=True, max_length=500)),
                ('estrofe_img', models.ImageField(blank=True, default='fallback.jpg', upload_to='')),
                ('audio_pt', models.FileField(blank=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Os Lusíadas',
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500)),
                ('author', models.CharField(max_length=100)),
                ('book', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('OK', 'Public, aproved!'), ('Waiting', 'Private, waiting for aproval...')], default='Waiting')),
            ],
            options={
                'verbose_name_plural': 'Quotes',
            },
        ),
        migrations.CreateModel(
            name='Subscribed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Subscribed',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.URLField()),
                ('title', models.CharField(max_length=100)),
                ('img', models.ImageField(default='fallback.jpg', upload_to='')),
                ('alt', models.CharField(blank=True, default='Capa do vídeo', max_length=100)),
                ('ogdate', models.DateField(blank=True, default=datetime.date.today)),
                ('author', models.CharField(blank=True, default='Anonymous', max_length=100)),
                ('date', models.DateField(blank=True, verbose_name=datetime.date.today)),
                ('status', models.CharField(choices=[('OK', 'Public, aproved!'), ('Waiting', 'Private, waiting for aproval...')], default='Waiting')),
            ],
            options={
                'verbose_name_plural': 'Videos',
            },
        ),
    ]
