# Generated by Django 5.2.1 on 2025-07-03 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=100)),
                ('book', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Quotes',
            },
        ),
    ]
