# Generated by Django 5.2.1 on 2025-07-03 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPages', '0002_quote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='date',
        ),
        migrations.AlterField(
            model_name='quote',
            name='book',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
