# Generated by Django 5.2.1 on 2025-07-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPages', '0003_remove_quote_date_alter_quote_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='book',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
