# Generated by Django 5.2.1 on 2025-07-06 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPages', '0004_alter_quote_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('image', models.ImageField(default='fallback.png', upload_to='')),
            ],
        ),
        migrations.AlterModelOptions(
            name='lusiadas',
            options={'verbose_name_plural': 'Lusiadas'},
        ),
    ]
