# Generated by Django 5.2.1 on 2025-07-06 19:37

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPages', '0005_galeria_alter_lusiadas_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='fallback.png', upload_to='')),
                ('author', models.CharField(blank=True, default='Anonymous', max_length=100)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('canto', models.CharField(blank=True, max_length=100)),
                ('alt', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField(blank=True, verbose_name=datetime.date.today)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.DeleteModel(
            name='Galeria',
        ),
    ]
