# Generated by Django 5.2.1 on 2025-07-06 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPages', '0006_image_delete_galeria'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='status',
            field=models.CharField(blank=True, choices=[('OK', 'Public, aproved'), ('Waiting', 'Private, waiting for aproval')], default='Private, waiting for aproval', max_length=50),
        ),
        migrations.AlterField(
            model_name='image',
            name='canto',
            field=models.CharField(blank=True, choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V'), ('VI', 'VI'), ('VII', 'VII'), ('VIII', 'VIII'), ('IX', 'IX'), ('X', 'X')], max_length=50),
        ),
    ]
