# Generated by Django 5.2.1 on 2025-07-07 11:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPages', '0007_image_status_alter_image_canto'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='status',
            field=models.CharField(blank=True, choices=[('OK', 'Public, aproved!'), ('Waiting', 'Private, waiting for aproval...')], default='Waiting'),
        ),
        migrations.AlterField(
            model_name='image',
            name='alt',
            field=models.CharField(blank=True, default='Image from workshop', max_length=100),
        ),
        migrations.AlterField(
            model_name='image',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(default='fallback.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='image',
            name='status',
            field=models.CharField(blank=True, choices=[('OK', 'Public, aproved!'), ('Waiting', 'Private, waiting for aproval...')], default='Waiting', max_length=50),
        ),
    ]
