# Generated by Django 5.2.1 on 2025-07-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPages', '0009_subscribed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lusiadas',
            name='content',
        ),
        migrations.RemoveField(
            model_name='lusiadas',
            name='titulo',
        ),
        migrations.AddField(
            model_name='lusiadas',
            name='canto',
            field=models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V'), ('VI', 'VI'), ('VII', 'VII'), ('VIII', 'VIII'), ('IX', 'IX'), ('X', 'X')], default='I'),
        ),
        migrations.AddField(
            model_name='lusiadas',
            name='estrofe',
            field=models.CharField(default='estrofe', max_length=500),
        ),
        migrations.AddField(
            model_name='lusiadas',
            name='estrofe_en',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='lusiadas',
            name='estrofe_id',
            field=models.CharField(default=None, max_length=4),
        ),
    ]
