# Generated by Django 5.2.1 on 2025-07-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPages', '0010_remove_lusiadas_content_remove_lusiadas_titulo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lusiadas',
            name='estrofe',
        ),
        migrations.AddField(
            model_name='lusiadas',
            name='estrofe_pt',
            field=models.TextField(default='estrofe', max_length=500),
        ),
        migrations.AlterField(
            model_name='lusiadas',
            name='estrofe_en',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
