# Generated by Django 5.2.1 on 2025-07-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPages', '0011_remove_lusiadas_estrofe_lusiadas_estrofe_pt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lusiadas',
            name='estrofe_img',
            field=models.ImageField(blank=True, default='fallback.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='lusiadas',
            name='estrofe_note',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
