# Generated by Django 5.2.1 on 2025-07-07 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPages', '0012_lusiadas_estrofe_img_lusiadas_estrofe_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='lusiadas',
            name='audio_pt',
            field=models.FileField(blank=True, upload_to='audio/'),
        ),
    ]
