# Generated by Django 5.2.4 on 2025-07-11 11:25

from django.db import migrations, models
from datetime import date

class Migration(migrations.Migration):

    dependencies = [
        ('mainPages', '0014_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='ogdate',
            field=models.DateField(default=date.today),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
