# Generated by Django 5.2.4 on 2025-07-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPages', '0015_video_ogdate_alter_video_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='ogdate',
            field=models.DateField(blank=True),
        ),
    ]
