# Generated by Django 5.2.4 on 2025-07-11 11:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPages', '0016_alter_video_ogdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='ogdate',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
