# Generated by Django 5.2.4 on 2025-07-11 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainPages', '0017_alter_video_ogdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
