# Generated by Django 5.2.4 on 2025-07-11 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainPages', '0019_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
