# Generated by Django 5.2.4 on 2025-07-11 12:31

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPages', '0021_video'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('img', models.ImageField(default='fallback.jpg', upload_to='')),
                ('alt', models.CharField(blank=True, default='Capa do PDF', max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(blank=True, default='Anonymous', max_length=100)),
                ('ogdate', models.DateField(blank=True, default=datetime.date.today)),
                ('status', models.CharField(blank=True, choices=[('OK', 'Public, aproved!'), ('Waiting', 'Private, waiting for aproval...')], default='Waiting', max_length=50)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Books',
            },
        ),
    ]
