# Generated by Django 5.2.4 on 2025-07-11 16:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPages', '0022_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(default=1500, validators=[django.core.validators.MinValueValidator(1300), django.core.validators.MaxValueValidator(2200)])),
                ('title', models.CharField(max_length=100)),
                ('summary', models.CharField(max_length=150)),
                ('content', models.CharField(blank=True, max_length=500)),
                ('img', models.ImageField(default='fallback.jpg', upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Events',
            },
        ),
    ]
