# Generated by Django 5.2.4 on 2025-07-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPages', '0023_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='content',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
